import {readFileSync} from "node:fs";
import {beforeEach,afterEach,it,expect,vi} from "vitest";
vi.mock("cloudflare:workers",()=>({WorkflowEntrypoint:class{env:unknown;constructor(_ctx:unknown,env:unknown){this.env=env;}}}));
import {AgentWorkflow} from "../../src/index";
import {UnboundedAgentWorkflow} from "../../src/unbounded/index";
import * as sources from "../../src/sources";
import * as discovery from "../../src/unbounded/discovery";
import {CHICAGO_OPERATIONS} from "../fixtures/candidates";
import {completePosting} from "../fixtures/policy-postings";
import {baselineSources} from "../../src/discovery/baseline";
import {createDatabase,loadSchema} from "./harness";
let db:D1Database,dispose:()=>Promise<void>;
beforeEach(async()=>{({db,dispose}=await createDatabase());await loadSchema(db,"root");vi.spyOn(console,"log").mockImplementation(()=>{});vi.spyOn(console,"error").mockImplementation(()=>{});});
afterEach(async()=>{vi.restoreAllMocks();vi.unstubAllGlobals();await dispose();});
it.each(["fixed","unbounded"])("%s worker retains retry without an assessed row for uncertain negatives",async kind=>{
 const instance=JSON.parse(readFileSync(new URL("../../examples/instance.json",import.meta.url),"utf8"));instance.screeningMode="legacy";
 await db.prepare("INSERT INTO fixed_baselines VALUES (?,?,?)").bind(instance.instanceId,baselineSources(CHICAGO_OPERATIONS.search.sources),"2026-01-01").run();
 const cases=['{"match":false,"reason":"unterminated','{"match":false}',JSON.stringify({match:false,lane:null,hard_exclude:"99",reason:"Unknown"}),JSON.stringify({match:false,lane:null,hard_exclude:null,reason:"No fit"})];
 const jobs=cases.map((_,i)=>completePosting({id:`greenhouse:Example Automation:${800+i}`,url:`https://job-boards.greenhouse.io/example-automation/jobs/${800+i}`,...(i===3?{contentProvenance:undefined}: {})}));
 jobs[3].contentProvenance=undefined;
 vi.spyOn(sources,"fetchAllPostings").mockResolvedValue({jobs,errors:[]});
 vi.spyOn(discovery,"findPostingsForPhrases").mockResolvedValue({refs:jobs.map((job,i)=>({ats:"greenhouse",slug:"example-automation",postingId:String(800+i),url:job.url,title:job.title})),errors:[]} as any);
 vi.spyOn(sources,"fetchPosting").mockImplementation(async ref=>jobs[Number(ref.postingId)-800]);
 const calls:number[]=[];vi.stubGlobal("fetch",vi.fn(async(input:any)=>{expect(String(input)).toBe("https://slack.com/api/chat.postMessage");return Response.json({ok:true});}));
 const AI={run:async(_model:string,input:any)=>{const text=input.messages[1].content;const id=Number(/jobs\/(80[0-3])/.exec(text)![1]);calls.push(id);return {choices:[{message:{tool_calls:[{function:{name:"record_verdict",arguments:cases[id-800]}}]},finish_reason:"tool_calls"}]};}};
 const Workflow=kind==="fixed"?AgentWorkflow:UnboundedAgentWorkflow;
 const env={DB:db,CANDIDATE_CONFIG:JSON.stringify(CHICAGO_OPERATIONS),INSTANCE_CONFIG:JSON.stringify(instance),AI,SLACK_BOT_TOKEN:"SYNTHETIC-BOT"};
 const step={do:async(_name:string,...args:any[])=>args.at(-1)(),sleep:async()=>{}};
 const pipeline=kind==="fixed"?"fixed_boards":"unbounded_discovery";
 const prefix=kind==="fixed"?"greenhouse:Example Automation:":"greenhouse:example-automation:";
 await db.prepare("INSERT INTO discovery_retries VALUES (?,?, 'filter',2,'earlier','synthetic',0,0)").bind(pipeline,prefix+"800").run();
 await new Workflow({} as any,env as any).run({instanceId:"uncertain-"+kind,payload:{}} as any,step as any);
 expect(calls).toHaveLength(7);expect(await db.prepare("SELECT count(*) n FROM jobs").first()).toEqual({n:0});
 expect((await db.prepare("SELECT job_id,attempts FROM discovery_retries ORDER BY job_id").all()).results).toEqual(cases.map((_,i)=>({job_id:prefix+(800+i),attempts:i===0?3:1})));
});
