import {it,expect,afterEach} from 'vitest';
import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createDatabase} from './harness';
import {applySchema,createResourcePlan,FakeResourceAdapter,ensureResources,localSetupDatabase,loadResourcePlan} from '../../tools/setup/resources';
import {activateReviewed,assertDrained,type ActivationReview} from '../../tools/setup/cli';
import {hashBytes,loadApprovedProfile} from '../../tools/setup/preflight';
import {CHICAGO_OPERATIONS,BOSTON_ENGINEERING} from '../fixtures/candidates';
const roots:string[]=[];const dbs:Array<Awaited<ReturnType<typeof createDatabase>>>=[];
afterEach(async()=>{for(const db of dbs.splice(0))await db.dispose();for(const r of roots.splice(0))await rm(r,{recursive:true,force:true});});
async function setup(){const root=await mkdtemp(join(tmpdir(),'activation-'));roots.push(root);const h=await createDatabase();dbs.push(h);const draft=JSON.parse(await readFile(new URL('../../examples/instance.draft.json',import.meta.url),'utf8'));const plan=await createResourcePlan(root,draft);const adapter=new FakeResourceAdapter(root,plan);const instance=await ensureResources(plan.instance,adapter);const db=localSetupDatabase(h.db);await applySchema(db,{instanceId:instance.instanceId,accountId:instance.cloudflare.accountId,databaseId:instance.cloudflare.databaseId},new URL('../..',import.meta.url).pathname);const c=structuredClone(CHICAGO_OPERATIONS);const readable='Reviewed synthetic criteria\n';c.approval.readableSha256=hashBytes(readable);await writeFile(join(root,'candidate.json'),JSON.stringify(c));await writeFile(join(root,'criteria.md'),readable);const runtime=await loadApprovedProfile(root);const review:ActivationReview={instanceId:instance.instanceId,instanceSha256:hashBytes(JSON.stringify(instance)),criteriaVersion:runtime.criteriaVersion,readableSha256:c.approval.readableSha256,resourceIds:Object.fromEntries((await loadResourcePlan(root)).intents.map(i=>[i.kind,i.id!])),expectedRevision:null,externalQuiesced:true,receiptsReconciled:true,evidence:'Synthetic workers not deployed; no schedules, sends or prior activation',reviewedAt:new Date().toISOString()};return {root,h,db,adapter,instance,runtime,review};}
it('activates only reviewed independent D1 criteria and reconciles lost CAS response exactly once',async()=>{const s=await setup();let lost=false;const faulty={batch:async(q:Parameters<typeof s.db.batch>[0])=>{const result=await s.db.batch(q);if(q.some(v=>v.sql.includes('INSERT INTO candidate_active_configs'))&&!lost){lost=true;throw new Error('lost CAS response');}return result;}};await expect(activateReviewed(s.root,s.instance,s.runtime,s.adapter,faulty,s.review)).rejects.toThrow('lost CAS response');expect(await activateReviewed(s.root,s.instance,s.runtime,s.adapter,s.db,s.review)).toBe(1);expect(await s.h.db.prepare('SELECT revision FROM candidate_active_configs').first()).toEqual({revision:1});expect(await s.h.db.prepare('SELECT COUNT(*) AS n FROM candidate_run_configs').first()).toEqual({n:0});});
it('refuses unknown Slack sends, active leases, stale revision and changed readable bytes',async()=>{const s=await setup();await s.h.db.prepare("INSERT INTO discovery_run_leases(pipeline,owner,fence,expires_at) VALUES ('fixed_boards','synthetic',1,?)").bind(Date.now()+60000).run();await expect(activateReviewed(s.root,s.instance,s.runtime,s.adapter,s.db,s.review)).rejects.toThrow('DELIVERY_NOT_DRAINED');await s.h.db.prepare('DELETE FROM discovery_run_leases').run();await s.h.db.prepare("INSERT INTO manual_intake_deliveries(id,request_id,job_id,state,updated_at) VALUES ('d','r','j','unknown','now')").run();await expect(assertDrained(s.db)).rejects.toThrow('DELIVERY_NOT_DRAINED');await s.h.db.prepare('DELETE FROM manual_intake_deliveries').run();await s.h.db.prepare('INSERT INTO candidate_active_configs VALUES (?,?,2,?)').bind(s.instance.instanceId,s.runtime.criteriaVersion,'now').run();await expect(activateReviewed(s.root,s.instance,s.runtime,s.adapter,s.db,s.review)).rejects.toThrow('ACTIVE_REVISION_CHANGED');await writeFile(join(s.root,'criteria.md'),'changed');await expect(activateReviewed(s.root,s.instance,s.runtime,s.adapter,s.db,s.review)).rejects.toThrow('READABLE_APPROVAL_MISMATCH');});
