import { it, expect, afterEach } from 'vitest';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createResourcePlan, FakeResourceAdapter, ensureResources, verifyResources, loadResourcePlan } from '../../tools/setup/resources';
import { withWorkspaceLock } from '../../tools/setup/state';
const roots: string[] = [];
afterEach(async () => { for (const r of roots.splice(0))
    await rm(r, { recursive: true, force: true }); });
async function setup() { const root = await mkdtemp(join(tmpdir(), 'setup-resources-')); roots.push(root); const raw = JSON.parse(await readFile(new URL('../../examples/instance.draft.json', import.meta.url), 'utf8')); const plan = await createResourcePlan(root, raw); const adapter = new FakeResourceAdapter(root, plan); return { root, plan, adapter }; }
it('uses fresh random names, resumes a lost creation response without duplicates and verifies every ID', async () => { const { root, plan, adapter } = await setup(); adapter.loseCreateResponse = 'database'; await expect(ensureResources(plan.instance, adapter)).rejects.toThrow('RESOURCE_CREATION_UNCERTAIN'); expect(adapter.records).toHaveLength(1); const result = await ensureResources(plan.instance, adapter); expect(adapter.records).toHaveLength(4); expect(result.cloudflare.databaseId).toBe(adapter.records[0].id); expect(result.cloudflare.databaseName).not.toBe('example-ledger'); expect(await ensureResources(result, adapter)).toEqual(result); expect(adapter.records).toHaveLength(4); await verifyResources(result, adapter); });
it('refuses foreign name collision, ambiguous ownership, missing and replaced resources', async () => { const { plan, adapter } = await setup(); adapter.records.push({ kind: 'database', id: crypto.randomUUID(), name: plan.instance.cloudflare.databaseName, instanceId: 'foreign', accountId: plan.instance.cloudflare.accountId }); await expect(ensureResources(plan.instance, adapter)).rejects.toThrow('RESOURCE_OWNERSHIP_CONFLICT'); adapter.records = []; const config = await ensureResources(plan.instance, adapter); adapter.records[0].instanceId = 'foreign'; await expect(verifyResources(config, adapter)).rejects.toThrow('RESOURCE_OWNERSHIP_CONFLICT'); adapter.records.shift(); await expect(ensureResources(config, adapter)).rejects.toThrow('RESOURCE_MISSING'); });
it('preserves completed migration receipts across partial failure and applies missing IDs once', async () => { const { plan, adapter } = await setup(); adapter.applied = ['ledger']; adapter.failAfterMigration = 2; await expect(ensureResources(plan.instance, adapter)).rejects.toThrow('MIGRATION_INTERRUPTED'); const first = [...adapter.applied]; const config = await ensureResources(plan.instance, adapter); expect(adapter.applied.slice(0, 2)).toEqual(first); expect(new Set(adapter.applied).size).toBe(adapter.applied.length); expect(await ensureResources(config, adapter)).toEqual(config); });
it('durably preserves the creation intent before any provider write and refuses different instance plan', async () => { const { root, plan } = await setup(); expect(await loadResourcePlan(root)).toEqual(plan); await expect(createResourcePlan(root, { ...plan.instance, instanceId: 'foreign' })).rejects.toThrow('INSTANCE_MISMATCH'); });
it('persists a recovered ID and refuses a replacement resource after response loss', async () => { const { root, plan, adapter } = await setup(); adapter.loseCreateResponse = 'database'; await expect(ensureResources(plan.instance, adapter)).rejects.toThrow('RESOURCE_CREATION_UNCERTAIN'); const config = await ensureResources(plan.instance, adapter); expect((await loadResourcePlan(root)).intents.find(i => i.kind === 'database')?.id).toBe(config.cloudflare.databaseId); });
it('real provider adapter uses metadata-only Worker creation with account-scoped opaque identity and no native instance tags', async () => { const { root, plan } = await setup(); const { WranglerResourceAdapter } = await import('../../tools/setup/resources'); const rows: Record<string, unknown>[] = []; const calls: Array<{
    path: string;
    method: string;
    body: unknown;
}> = []; const adapter = new WranglerResourceAdapter(root, plan, async (path, method, body) => { calls.push({ path, method, body }); if (method === 'POST') {
    const record = { id: 'opaque-worker-id', name: (body as any).name };
    rows.push(record);
    return { result: record };
} if (path.includes('?'))
    return { result: rows }; return { result: rows[0] }; }, new URL('../..', import.meta.url).pathname); const intent = plan.intents.find(i => i.kind === 'fixed_worker')!; const record = await adapter.create(intent); expect(record.id).toBe('opaque-worker-id'); expect((await adapter.read('fixed_worker', record.id, intent.accountId))?.instanceId).toBe(plan.instance.instanceId); expect(calls.filter(c => c.method === 'POST')).toEqual([{ path: `/accounts/${intent.accountId}/workers/workers`, method: 'POST', body: { name: intent.name, subdomain: { enabled: false, previews_enabled: false } } }]); });
it('resume preserves newly selected instance settings and refuses forged provisioned IDs', async () => { const { root, plan, adapter } = await setup(); const config = await ensureResources(plan.instance, adapter); const changed = { ...config, screeningMode: 'evidence' as const, manualScreeningMode: 'evidence' as const }; expect((await createResourcePlan(root, changed)).instance.screeningMode).toBe('evidence'); await expect(createResourcePlan(root, { ...changed, cloudflare: { ...changed.cloudflare, databaseId: crypto.randomUUID() } })).rejects.toThrow('RESOURCE_ID_CHANGED'); });
it('new setup process resumes from persisted intents and rejects ambiguous exact-name matches',async()=>{const {root,plan,adapter}=await setup();adapter.loseCreateResponse='database';await expect(ensureResources(plan.instance,adapter)).rejects.toThrow('RESOURCE_CREATION_UNCERTAIN');const restored=await loadResourcePlan(root);const resumed=new FakeResourceAdapter(root,restored);resumed.records=adapter.records;const config=await ensureResources(restored.instance,resumed);expect(resumed.records).toHaveLength(4);resumed.records.push({...resumed.records[0],id:crypto.randomUUID()});await expect(ensureResources(config,resumed)).rejects.toThrow('RESOURCE_AMBIGUOUS');});
it('fake fresh-schema lost response models one atomic represented receipt set',async()=>{const {plan,adapter}=await setup();adapter.failAfterMigration=2;await expect(ensureResources(plan.instance,adapter)).rejects.toThrow('MIGRATION_INTERRUPTED');expect(adapter.applied).toHaveLength(14);await ensureResources(plan.instance,adapter);expect(new Set(adapter.applied).size).toBe(14);});
